title: Guia Java com MS e Cloud
description: Conteúdo prático para backend Java com microsserviços e cloud
remote_theme: pmarsceill/just-the-docs

url: https://andersonaoliveira.github.io

baseurl: "/java-microsservicos-cloud-guia-pratico"

just_the_docs:
  logo: "/assets/imagens/capa.png"
  show_downloads: false
  search_enabled: true
  nav_sort: case_sensitive
