title: Java para Microsserviços e Cloud
description: Um guia prático para backend moderno
url: "https://andersonaoliveira.github.io"
baseurl: "/java-microsservicos-cloud-guia-pratico"

theme: just-the-docs

just_the_docs:
  logo: "/assets/imagens/capa.png"
  aux_links:
    GitHub: https://github.com/andersonaoliveira/java-microsservicos-cloud-guia-pratico
  search_enabled: true